name: "Test"
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  test:
    name: Test (${{ matrix.os }}) - (CLI ${{ matrix.cli-version || 'default' }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ${{ github.actor == 'dependabot[bot]' && fromJSON('["ubuntu-latest"]') || fromJSON('["ubuntu-latest", "macos-13", "windows-latest"]') }}
        cli-version: [ "", "latest", "1.46.4" ]
      fail-fast: false
    steps:
      # Checkout and install prerequisites
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: "20.x"

      # Run action according to the input version
      - name: Setup JFrog CLI
        if: matrix.cli-version != ''
        uses: ./
        with:
          version: ${{ matrix.cli-version }}
      - name: Setup default JFrog CLI
        if: matrix.cli-version == ''
        uses: ./

      # Run --version
      - name: Check versions
        run: jf --version && jfrog --version

      # Check local server successfully configured
      - name: Sanity
        run: jf c show local || jfrog rt config show local

      # Check build URL
      - name: Check build URL
        run: curl -I "$JFROG_CLI_BUILD_URL"
        shell: bash

      # Check environment variables
      - name: Check action environment
        run: node scripts/check-env.js

      # Install and run tests
      - name: Install
        run: npm i
      - name: Unit tests
        run: npm t
